language: cpp
os: linux
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake mpich2 liblapack-dev libboost-filesystem-dev libboost-system-dev python-numpy ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install pyamg ; fi
before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_UNIT_TESTS=yes ..
script: make && make test
